### ISSUE TITLE
errors at bazel build for tensorflow

### ISSUE THREAD

**Issue by ron333** [tfors/rpi-tf#1]
pi@raspberrypi:~/tensorflow/bazel/tensorflow $ bazel build -c opt --copt="-mfpu=neon-vfpv4" \
>     --copt="-funsafe-math-optimizations" \
>     --copt="-ftree-vectorize" \
>     --copt="-fomit-frame-pointer" \
>     --local_resources 1024,1.0,1.0 \
>     --verbose_failures tensorflow/tools/pip_package:build_pip_package
ERROR: /home/pi/tensorflow/bazel/tensorflow/tensorflow/workspace.bzl:182:3: syntax error at 'native': expected ,
ERROR: /home/pi/tensorflow/bazel/tensorflow/tensorflow/workspace.bzl:191:3: non-keyword arg after keyword arg.
ERROR: /home/pi/tensorflow/bazel/tensorflow/tensorflow/workspace.bzl:201:3: Trailing comma is allowed only in parenthesized tuples.
ERROR: /home/pi/tensorflow/bazel/tensorflow/tensorflow/workspace.bzl:222:3: Trailing comma is allowed only in parenthesized tuples.
ERROR: /home/pi/tensorflow/bazel/tensorflow/tensorflow/workspace.bzl:238:3: Trailing comma is allowed only in parenthesized tuples.
ERROR: error loading package '': Extension 'tensorflow/workspace.bzl' has errors

**Comment by tfors** [comment]
Can you double-check the edits to `tensorflow/workspace.bzl`? The error
messages lead me to believe there might be a comma missing near line 182.

**Comment by ron333** [comment]
Thanks for looking into this.  I re-edited 'tensorflow/workspace.bzl' and things worked fine.
